set-option -g mouse on
set-option -g default-terminal "tmux-256color"
set-option -a terminal-features '*:RGB'

bind -n M-1 select-layout even-horizontal
bind -n M-2 select-layout even-vertical
bind -n M-3 select-layout main-horizontal
bind -n M-4 select-layout main-vertical
bind -n M-5 select-layout tiled

set-option -g status-style "bg=#{?client_prefix,yellow,green},fg=black"

# For main-vertical (left pane is 50% width)
set-window-option -g main-pane-width 50%

# For main-horizontal (top pane is 50% height)
set-window-option -g main-pane-height 50%

bind M-Left select-pane -L
bind M-Right select-pane -R
bind M-Up select-pane -U
bind M-Down select-pane -D

# Smart merge: join pane in the opposite axis
bind S-Left join-pane -v -s '{left-of}'
bind S-Right join-pane -v -s '{right-of}'
bind S-Up join-pane -h -s '{up-of}'
bind S-Down join-pane -h -s '{down-of}'

# Easier Split Navigation
bind - split-window -v
bind '|' split-window -h
unbind '"'
unbind %

# Start Indexing at 1
set -g base-index 1
setw -g pane-base-index 1

# Increase Scrollback Buffer
set -g history-limit 10000

set -g focus-events on

# Remove escape delay
set -s escape-time 0

# Vim keys in copy mode
set-window-option -g mode-keys vi

# Auto-renumber windows
set -g renumber-windows on

# Repeatable pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Fuzzy search scrollback history and jump to the selected line in copy-mode
bind f run-shell 'line=$(tmux capture-pane -S - -p | fzf-tmux -p 80%,60% --no-sort --exact) && [ -n "$line" ] && tmux copy-mode && tmux send-keys -X search-backward-text "$line"'

# Fuzzy switch sessions
bind g display-popup -E "tmux list-sessions | fzf --reverse | cut -d: -f1 | xargs tmux switch-client -t"

# Copy selection on mouse release and clear highlighting but don't exit copy-mode
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "pbcopy"

# Auto-set terminal window title
set-option -g set-titles on
set-option -g set-titles-string "#S: #W"
